### ISSUE TITLE
here is your windows version of it

### ISSUE THREAD

**Issue by Jonnycatmeow** [tgpethan/holly-engine-fnf#1]
i wanrted to make one so people don't have to build it  

[holly engine build ](https://www.mediafire.com/file/8p3nlqd1taj4hgl/holly_engine.zip/file) 

its 64 bit version

**Comment by tgpethan** [comment]
I develop on linux but do have a windows dev vm.

Thanks for going to the effort of building this (and actually finding my for fun project) but this is *really* unfinished and fairly useless as it stands also random executables built by an unknown source isn't really something I trust.
